name: Scrape_Sfw

on:
  schedule:
    - cron: "0 0 6 6 9 ? " #"0 13,15,17,19,21,23 * * *" #"0 13-23/2 * * *" 
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install Python requirements
        run: pip install python-twitter-v2 praw requests #-U redgifs #-r requirements.txt
      - name: Run scrape_and_post_sfw
        run: python main_sfw.py ${{secrets.REDDIT_CLIENT_ID}} ${{secrets.REDDIT_CLIENT_SECRET}} ${{secrets.REDDIT_PASSWORD}} ${{secrets.REDDIT_USER_AGENT}} ${{secrets.REDDIT_USER_NAME}} ${{secrets.TWITTER_ACCESS_TOKEN_SFW}} ${{secrets.TWITTER_ACCESS_TOKEN_SECRET_SFW}} ${{secrets.TWITTER_CONSUMER_KEY_SFW}} ${{secrets.TWITTER_CONSUMER_SECRET_SFW}} 
      #- name: Set env vars
      #  run: |
      #    echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
      #- name: Push to repository
      #  run: |
      #    git config --global user.name "whs2k"
      #    git config --global user.email ${{secrets.GIT_USER_EMAIL}}
      #    now=$(date)
      #    git add -A
      #    git commit -m "Auto Push on $now"
      #    git push
